# read from HDF5 generated by ../bgen2hdf5/geno_hdf5.py

import h5py

def get_individual_list(hdf5):
    with h5py.File(hdf5, 'r') as f:
        indiv = f['samples'][:].astype(str)
    return indiv
    