pedigree:
  path: '/lambda_stor/data/yanyul/Framingham/haplotype_po_framingham/preprocess/extracted_pedigree.tsv.gz'
  child_col: 'shareid'
  father_col: 'fshare'
  mother_col: 'mshare'
vcf: '/lambda_stor/data/yanyul/Framingham/imputed_hrc1.1/chr{chr_num}.dose.vcf.gz'
bvftools_path: '/lambda_stor/data/yanyul/softwares/bcftools-1.10.2/bcftools' 
outdir: '/lambda_stor/data/yanyul/Framingham/haplotype_po_framingham/infer_ho_from_genotype'
maf_filter: 0.05  # use for post analysis

name_tag: 'from_extracted_pedigree'
chromosomes:
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
  - 10
  - 11
  - 12
  - 13
  - 14
  - 15
  - 16
  - 17
  - 18
  - 19
  - 20
  - 21
  - 22

