obs_expr: '/lambda_stor/data/yanyul/Framingham/haplotype_po_framingham/prepare_for_imputation/obs_expr.tsv.gz'
covariate: '/lambda_stor/data/yanyul/Framingham/haplotype_po_framingham/prepare_for_imputation/covariate.tsv.gz'
pedigree: '/lambda_stor/data/yanyul/Framingham/haplotype_po_framingham/preprocess/extracted_pedigree.tsv.gz'

pred_expr: '/lambda_stor/data/yanyul/Framingham/haplotype_po_framingham/pred_expr/gtex_v8_Whole_Blood_{name_tag}.pred_expr_{chr_num}.txt'

chromosomes: 
  - 1
  - 2
  # - 3
  # - 4
  # - 5
  # - 6
  # - 7
  # - 8
  # - 9
  # - 10
  # - 11
  # - 12
  # - 13
  # - 14
  # - 15
  # - 16
  # - 17
  # - 18
  # - 19
  # - 20
  # - 21
  # - 22

# name_tag: 'en'