---
title: "Home"
date: "`r paste0('Last update: ', format(Sys.time(), '%b %d, %Y'))`"    
---

# Notes

* [Initial thoughts](init_idea_outline.html). The full pipeline [imputation + GWAS](impute_and_gwas.html).
* [Power comparison on haplotype-based GWAS](haplo_gwas_power.html).
* [Logistic solver (single SNP case)](logistic_solver_single.html).
* [Second thought on how to do haplotype imputation (on-the-fly OTF)](second_idea_outline.html). Along this line, [the variation with logistic model replacing linear model](second_idea_outline_logistic.html). Also, [per-SNP likelihood replacing the PRS model](second_idea_outline_per_snp.html).

# Real data analysis

* [Initial look at parent illness in UK Biobank](parent_illness_init.html).
* [Second try at querying illness in UK Biobank](parent_illness_2nd.html): Include instance 0, 1, and 2 (instance 3 is not on Bionimbus).
* [What GWAS to use?: Neale's lab UK Biobank GWAS](gwas_neale_lab_ukb.html)
* [Sanity check runs](sanity_check.html)
* Framingham data detour. [Modified imputation scheme from PRS-based initial try](init_idea_a_variation.html). [Imputation results compared to "ground truth"](framingham_results.html)
