gwas: 
  '/vol/bmd/yanyul/UKB/neale_lab_gwas/{gwas_name}.tsv.bgz'
  # '/scratch/t.cri.yliang/haplotype-po/neale_lab_gwas/{gwas_name}.tsv.bgz'  
snp_map: '/vol/bmd/yanyul/UKB/haplotype_imputation/snp_map_for_neale_lab_gwas.tsv.gz'
genotype:
  vcf: 
    '/vol/bmd/yanyul/UKB/haplotype_imputation/subset_britich_cleaned_up_vcf/renamed.chr{chr_num}.vcf.gz'
    # '/scratch/t.cri.yliang/haplotype-po/subset_britich_cleaned_up_vcf/renamed.chr{chr_num}.vcf.gz'  
snp_field: 'variant'
pval_field: 'pval'
plink_memory_in_mb: 16000
plink_threads: 1
plink_cmd: 
  '/vol/bmd/yanyul/softwares/plink' 
  # 'plink' 
outdir: 
  '/vol/bmd/yanyul/UKB/haplotype_imputation/ld_clump'
  # '/scratch/t.cri.yliang/haplotype-po/ld_clump'
extract_by_column_rscript: '/vol/bmd/yanyul/GitHub/ptrs-ukb/code/extract_by_column.R'
