bgen: 
  '/vol/bmd/yanyul/UKB/subset_bgen_full_variant/subset_chr{chr_num}.bgen'
  # '/gpfs/data/im-lab/nas40t2/yanyul/PTRS/subset_bgen/subset_chr{chr_num}.bgen'
sample:
  '/vol/bmd/yanyul/UKB/subset_bgen_full_variant/subset_chr{chr_num}.sample' 
  # '/gpfs/data/im-lab/nas40t2/yanyul/PTRS/subset_bgen/subset_chr{chr_num}.sample'
plink2_cmd:
  '/vol/bmd/yanyul/softwares/plink2'
  # '/gpfs/data/im-lab/nas40t2/yanyul/softwares/plink2'
bcftools_cmd: '/vol/bmd/yanyul/softwares/bcftools-1.10/bcftools'
plink_memory_in_mb: 16000
plink_threads: 1
outdir:
  '/vol/bmd/yanyul/UKB/haplotype_imputation/subset_britich_cleaned_up_vcf' 
  # '/scratch/t.cri.yliang/haplotype-po/subset_britich_cleaned_up_vcf'
